\\ Generate a human-readable LaTeX companion for an arithmetic certificate.
\\
\\ Reads certificate/K-2800905-p5/certificate.gp and writes
\\ certificate/K-2800905-p5/certificate-guide.tex.  The guide restates, for
\\ every entry, the stored objects in the notation of Section 2.5 of the
\\ paper, together with facts that this script itself recomputes exactly
\\ (the relation div(a') + 5J = 0, ideal norms, degrees).  The heavy
\\ verification (AC1, AC2, Artin normalization, norm classes) remains the
\\ job of verify_certificate.c; this guide is exposition, not a checker.
\\
\\ Run from the repository root:
\\   gp -qf tools/certificate_guide.gp
\\ then compile certificate-guide.tex with pdflatex.

certpath = "certificate/K-2800905-p5/certificate.gp";
outpath  = "certificate/K-2800905-p5/certificate-guide.tex";

readcert() =
{
  my(rawlines = readstr(certpath), rawtext = "");
  for (i = 1, #rawlines, rawtext = concat(rawtext, rawlines[i]));
  eval(rawtext);
}

cert = readcert();
pp       = cert[3];
basepol  = cert[4];
basedisc = cert[5];
basedata = cert[6];
entries  = cert[7];
K = nfinit(basepol);

out(s) = write(outpath, s);

\\ chunk a plain string into lines of at most `width` characters
chunk(s, width) =
{
  my(codes = Vecsmall(s), pieces = [], from = 1, to);
  while (from <= #codes,
    to = min(from + width - 1, #codes);
    pieces = concat(pieces, [Strchr(codes[from..to])]);
    from = to + 1);
  pieces;
}

\\ emit a long GP expression as wrapped typewriter lines; the only
\\ TeX-special character occurring in these strings is the caret
emitverb(s) =
{
  my(pieces = chunk(s, 68), line);
  out("\\begin{quote}\\small\\ttfamily");
  for (i = 1, #pieces,
    line = strjoin(strsplit(Str(pieces[i]), "^"), "\\string^");
    out(concat(line, "\\\\")));
  out("\\end{quote}");
}

\\ render a factorization as 2\cdot 3^{4}\cdot ...
factorstring(n) =
{
  my(f = factor(n), parts = []);
  for (i = 1, matsize(f)[1],
    parts = concat(parts,
      [if (f[i,2] == 1, Str(f[i,1]),
           concat([Str(f[i,1]), "^{", Str(f[i,2]), "}"]))]));
  strjoin(parts, "\\cdot ");
}

emit_header() =
{
  system(concat("rm -f ", outpath));
  out("\\documentclass[11pt]{article}");
  out("\\usepackage[a4paper,margin=24mm]{geometry}");
  out("\\usepackage[T1]{fontenc}");
  out("\\usepackage[utf8]{inputenc}");
  out("\\usepackage{lmodern}");
  out("\\usepackage{amsmath,amssymb}");
  \\ PARI's strtex emits plain-TeX \pmatrix{..&..\cr..}; restore it.
  out("\\makeatletter");
  out("\\def\\pmatrix#1{\\left(\\vcenter{\\normalbaselines\\m@th");
  out("  \\ialign{\\hfil$##$\\hfil&&\\quad\\hfil$##$\\hfil\\crcr#1\\crcr}}\\right)}");
  out("\\makeatother");
  out("\\setlength{\\parindent}{0pt}");
  out("\\title{A guide to the arithmetic certificate for $K=\\mathbf Q(\\sqrt{-2800905})$, $p=5$}");
  out("\\author{}");
  out("\\date{Generated by \\texttt{tools/certificate\\_guide.gp}}");
  out("\\begin{document}");
  out("\\maketitle");
  out("\\section*{What this document is}");
  out("This guide restates the content of \\texttt{certificate.gp} in the");
  out("notation of Section~2.5 of the paper.  Each of the 27 entries");
  out("certifies one value $D_x(e_j)$ of a secondary norm operator: it");
  out("stores the unramified cyclic quintic $L_x/K$, the normalized");
  out("generator $\\sigma_x$, the pair $(a',J)$ representing the torsion");
  out("class $e_j$, the auxiliary divisor $I'$, the compactly represented");
  out("element $t$, a residue prime for the sign check, and the expected");
  out("norm class $[N_x(I')]$.  The two defining equations are");
  out("\\begin{align*}");
  out("(1-\\sigma_x)^2I'+\\operatorname{div}(t)+i_x(J)&=0,&");
  out("N_x(t)&=a'.");
  out("\\end{align*}");
  out("Facts marked \\emph{checked} are recomputed exactly by the");
  out("generating script; the full verification is performed by");
  out("\\texttt{verify\\_certificate.c} as described in the README of");
  out("this directory.");
  out("\\section*{Base field data}");
  out(concat(["The base field is $K=\\mathbf Q(s)$ with $",
      strtex(basepol), "=0$, of discriminant $", strtex(basedisc), "$."]));
  out(concat(["Class group invariants $", strtex(basedata[1]),
      "$, class number $", strtex(basedata[2]), "$;"]));
  out("the three stored generator ideals (HNF) are");
  out(concat(["$", strtex(basedata[3][1]), "$, $",
      strtex(basedata[3][2]), "$, $", strtex(basedata[3][3]), "$,"]));
  out(concat(["and the torsion units are generated by $",
      strtex(basedata[5]), "$ of order $", Str(basedata[4]), "$."]));
}

emit_entry(n) =
{
  my(e = entries[n], label, column, chi, relpol, abspol, sigma, aprime,
     J, Iprime, tfac, ell, q, expected, nJ, nI, okrel);
  label = e[1]; column = e[2]; chi = e[3]; relpol = e[4]; abspol = e[5];
  sigma = e[6]; aprime = e[7]; J = e[8]; Iprime = e[9]; tfac = e[10];
  ell = e[11]; q = e[12]; expected = e[13];

  out(concat(["\\section*{Entry ", Str(n), ": character $",
      Str(label), "$, column $e_{", Str(column), "}$}"]));
  out(concat(["Prescribed character vector $", strtex(chi~), "$."]));

  out("\\subsection*{The extension and its normalized generator}");
  out("Relative polynomial of $L_x$ over $K$:");
  out(concat(["\\[", strtex(relpol), "\\]"]));
  out("Absolute polynomial of $L_x$ over $\\mathbf Q$ (degree 10):");
  emitverb(Str(abspol));
  out("Coordinates of $\\sigma_x$ in the absolute integral basis:");
  out(concat(["$", strtex(sigma~), "$."]));

  out("\\subsection*{The pair $(a',J)$ representing the torsion class}");
  out(concat(["\\[ a' = ", strtex(aprime[1]), " + \\bigl(",
      strtex(aprime[2]), "\\bigr)\\,s, \\qquad J = ", strtex(J),
      ". \\]"]));
  nJ = idealnorm(K, J);
  okrel = idealhnf(K, idealmul(K, idealhnf(K, aprime),
                               idealpow(K, J, pp)))
          == idealhnf(K, 1);
  out(concat(["$N(J)=", Str(nJ), "$.  \\emph{Checked:} $(a')\\,J^{",
      Str(pp), "}=\\mathcal O_K$, equivalently $\\operatorname{div}(a')+",
      Str(pp), "J=0$: ",
      if(okrel, "\\textbf{pass}", "\\textbf{FAIL}"), "."]));

  out("\\subsection*{The auxiliary pair $(t,I')$}");
  nI = matdet(Iprime);
  out(concat(["$I'$ is stored as a $10\\times10$ HNF matrix in the",
      " absolute model; its absolute norm is $", Str(nI), " = ",
      factorstring(nI), "$."]));
  out(concat(["The element $t$ is stored in compact form as a product",
      " of $", Str(matsize(tfac)[1]),
      "$ factors with signed exponents of absolute value up to $",
      Str(vecmax(abs(tfac[,2]))),
      "$; it is never expanded (its principal ideal and residues are",
      " evaluated factor by factor)."]));

  out("\\subsection*{Sign check and certified value}");
  out(concat(["Residue prime: the stored prime ideal above $\\ell=",
      Str(ell), "$ with residue degree $", Str(q[4]),
      "$; there the quotient $N_x(t)/a'$ reduces to the residue of",
      " $+1$."]));
  out(concat(["Certified value: $D_x(e_{", Str(column), "}) = ",
      strtex(expected~), "$ in the coordinates of",
      " $\\operatorname{Cl}(K)/5$."]));
}

emit_header();
for (n = 1, #entries, emit_entry(n));
out("\\end{document}");
print("guide written: ", outpath, " (entries: ", #entries, ")");
quit
