#!/usr/bin/env python3
"""Print the norm-degeneracy scheme of the principal example.

Deterministic companion to the appendix subsection displaying Sigma_D
for D_K = -11203620: the polarized matrix of quadratic forms, the nine
2x2 minors, and the complete list of closed points with their tangent
dimensions.  Completeness of the point list is established by a
disjoint chart decomposition of the projective plane: on {w=1} the
Singular radical of the minor ideal is zero-dimensional and its
vector-space dimension counts the points with their residue degrees;
on {w=0, v=1} the ideal is generated by one squarefree univariate
polynomial, whose irreducible factors are counted directly; the
remaining point (1:0:0) is tested by evaluation.

Everything is derived from the committed file
certificates/p5/K-2800905-p5/secondary-norms.gp.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

spec = importlib.util.spec_from_file_location(
    "tro", ROOT / "tools" / "transverse_rank_one.py")
tro = importlib.util.module_from_spec(spec)
sys.modules["tro"] = tro
spec.loader.exec_module(tro)

P = 5
VARS = "uvw"


def poly_str(d):
    def mono(e):
        out = ""
        for var, exp in zip(VARS, e):
            if exp == 1:
                out += var
            elif exp > 1:
                out += f"{var}^{exp}"
        return out or "1"

    terms = sorted(d.items(),
                   key=lambda kv: (-sum(kv[0]),
                                   tuple(-x for x in kv[0])))
    parts = []
    for e, c in terms:
        if not c:
            continue
        m = mono(e)
        parts.append(m if c == 1 and m != "1" else f"{c}{m}" if m != "1"
                     else f"{c}")
    return " + ".join(parts) if parts else "0"


def factor_univariate(coeffs):
    """Irreducible factor degrees of a univariate polynomial over F_5,
    by distinct-degree splitting through root counting over F_{5^d}."""
    k_by_d = {d: tro.GF(d) for d in range(1, len(coeffs))}
    degree = len(coeffs) - 1
    counts = {}
    accounted = 0
    for d in sorted(k_by_d):
        if accounted >= degree:
            break
        k = k_by_d[d]
        roots = [x for x in k.elements()
                 if k.is_zero(k.poly_eval(coeffs, x))]
        exact = len(roots) - sum(e * counts.get(e, 0)
                                 for e in counts if d % e == 0)
        if exact:
            assert exact % d == 0
            counts[d] = exact // d
            accounted += exact
    assert accounted == degree, "polynomial is not squarefree over F_5"
    return counts


def main():
    text = (ROOT / "certificates/p5/K-2800905-p5/secondary-norms.gp").read_text()
    mats = tro.parse_gp_matrices(text, "secondary_norm_samples")[:6]
    basis, pairs = mats[0:3], mats[3:6]
    Dsym = tro.symbolic_D(basis, pairs)
    minors = tro.minors2(Dsym)

    print("Matrix of quadratic forms D_(u,v,w), columns = D_x(e_j):")
    for row in Dsym:
        print("  [ " + " | ".join(poly_str(e) for e in row) + " ]")
    print()
    print("The nine 2x2 minors (homogeneous quartics):")
    for i, m in enumerate(minors, 1):
        print(f"  m{i} = {poly_str(m)}")
    print()

    charts = tro.chart_ideals(minors)

    # Chart {w=1}: vdim of the radical counts points with residue degree.
    gens = ",\n  ".join(tro.poly2_str(tro.subst_w1(m))
                        for m in minors if m)
    script = (
        'LIB "primdec.lib";\n'
        'ring R = 5, (u, v), lp;\n'
        f'ideal I = {gens};\n'
        'ideal s = std(radical(I));\n'
        '"@VDIM";\n'
        'vdim(s);\n'
        'quit;\n')
    out = subprocess.run(["Singular", "-q"], input=script, text=True,
                         capture_output=True, timeout=300).stdout
    vdim = None
    take = False
    for line in out.splitlines():
        if line.strip() == "@VDIM":
            take = True
        elif take:
            vdim = int(line.strip())
            break
    print(f"Chart w=1: dim_F5 of the reduced coordinate ring = {vdim}")

    # Chart {w=0, v=1}: one squarefree univariate generator.
    polysB = [q for q in (tro.subst_v1w0(m) for m in minors) if q]
    genB = charts["B"]
    assert genB, "chart B ideal unexpectedly trivial"
    elim = genB[0]
    exps = [key[0] for key in elim]
    assert all(len(key) == 1 or all(e == 0 for e in key[1:])
               for key in elim)
    coeffs = [0] * (max(exps) + 1)
    for key, c in elim.items():
        coeffs[key[0]] = c
    counts = factor_univariate(coeffs)
    pretty = ", ".join(f"{n} of degree {d}" for d, n in sorted(counts.items()))
    print(f"Chart w=0, v=1: generator of degree {len(coeffs)-1}, "
          f"irreducible factors: {pretty}")

    # Remaining point (1:0:0): each minor is a homogeneous quartic, so
    # its value there is the coefficient of u^4.
    on_scheme = all(m.get((4, 0, 0), 0) % P == 0 for m in minors)
    print(f"Point (1:0:0) on Sigma_D: {on_scheme}")
    print()

    k_by_d = {d: tro.GF(d) for d in (1, 2, 3, 4, 5, 6)}
    k1 = k_by_d[1]
    print("Closed points with rank and tangent dimension:")
    for lam in tro.projective_points():
        x = [k1.from_int(c) for c in lam]
        cert = tro.certificate_at(k1, basis, pairs, x)
        if cert["rank"] == 1:
            td = tro.tangent_dim(k1, tro.minors2(Dsym), x)
            print(f"  degree 1: x = {lam}, rank 1, tangent dim {td}, "
                  f"transverse: {cert['transverse']}")
    for d, x, k in tro.find_points(tro.minors2(Dsym), k_by_d):
        if d == 1:
            continue
        cert = tro.certificate_at(k, basis, pairs, x)
        td = tro.tangent_dim(k, tro.minors2(Dsym), x)
        print(f"  degree {d}: rank {cert['rank']}, tangent dim {td}, "
              f"transverse: {cert.get('transverse')}")


if __name__ == "__main__":
    main()
